CSE343-Software_Engineering/Term-Project/accounts/urls.py
from django.urls import path, re_path, reverse_lazy, include
from .views import *
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('register/', signup, name='register'),
    path('logout/', logout_view, name='logout'),
    path('profile/', view_profile, name='profile'),
    path('edit_profile/', update_profile, name='edit_profile'),
    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='accounts/password_reset.html',
        email_template_name='accounts/password_reset_email.html',
        subject_template_name='accounts/password_reset_subject.txt',
        success_url=reverse_lazy('accounts:password_reset_done')
    ), name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(
        template_name='accounts/password_reset_done.html'
    ), name='password_reset_done'),
    path('password_reset_<uidb64>_<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='accounts/password_reset_confirm.html',
        success_url=reverse_lazy('accounts:password_reset_complete')
    ), name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='accounts/password_reset_complete.html'
    ), name='password_reset_complete'),
]

CSE343-Software_Engineering/Term-Project/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from home.views import home_view
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name="home"),
    path('post/', include('post.urls')),
    path('accounts/', include('accounts.urls')),
    path('trainer/', include('trainer.urls')),
    path('feedback/', include('feedback.urls')),
    path("stripe/", include("djstripe.urls", namespace="djstripe")),
    path('messaging/', include('messaging.urls')),

    path('payment/', include('payment.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CSE343-Software_Engineering/Term-Project/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='Account')
    bio = models.TextField(max_length=500, blank=True, verbose_name='Bio')
    location = models.CharField(max_length=30, blank=True, verbose_name='City')
    birth_date = models.DateField(null=True, blank=True, verbose_name='Birth Date')
    avatar_image = models.ImageField(null=True, blank=True, verbose_name='Profile Photo')

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

CSE343-Software_Engineering/Term-Project/accounts/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

class LoginForm(forms.Form):
    username = forms.CharField(max_length=100, label='Username')
    password = forms.CharField(max_length=100, label='Password', widget=forms.PasswordInput)

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError('Username or password is wrong!')
        return super(LoginForm, self).clean()

class RegisterForm(forms.ModelForm):
    username = forms.CharField(max_length=100, label='Username')
    password1 = forms.CharField(max_length=100, label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(max_length=100, label='Password Again', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = [
            'username',
            'password1',
            'password2',
        ]

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('Passwords does not match!')
        return password2

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Not required.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Not required.')
    email = forms.EmailField(max_length=254, help_text='Required. Please enter a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('bio', 'location', 'birth_date', 'avatar_image')

CSE343-Software_Engineering/Term-Project/accounts/views.py
from django.shortcuts import render, redirect
from .models import Profile
from .forms import LoginForm, RegisterForm, SignUpForm, UserForm, ProfileForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import Group
from django.contrib import messages
from django.core.mail import send_mail
from django.conf import settings

def login_view(request):
    form = LoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        login(request, user)
        return redirect('home')
    return render(request, 'accounts/form.html', {'form': form, 'title': 'Log In'})

def register_view(request):
    form = RegisterForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        password = form.cleaned_data.get('password1')
        user.set_password(password)
        user.save()
        new_user = authenticate(username=user.username,password=password)
        login(request, new_user)
        return redirect('home')
    return render(request, 'accounts/form.html', {'form': form, 'title': 'Sign Up'})

def logout_view(request):
    logout(request)
    return redirect('home')

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            group = Group.objects.get(name='customer')
            user.groups.add(group)
            login(request, user)
            return redirect('home')
    else:
        form = SignUpForm()
    return render(request, 'accounts/form.html', {'form': form, 'title': 'Sign Up'})

def update_profile(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, request.FILES or None, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Your profile was successfully updated!')
            return redirect('accounts:profile')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'accounts/edit_profile.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })

def view_profile(request):
    user = request.user

    context = {
        'user': user,
    }
    return render(request, 'accounts/view_profile.html', context)

CSE343-Software_Engineering/Term-Project/templates/accounts/edit_profile.html
{% load crispy_forms_tags %}
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Fitblog</title>
    <link rel="stylesheet" href="{% static 'css/Button.css' %}" />
    <link rel="stylesheet" href="{% static 'css/Link.css' %}" />
	<link rel="stylesheet" href="{% static 'css/Header.css' %}" />
	<link rel="stylesheet" href="{% static 'css/Footer.css' %}" />
	<link rel="stylesheet" href="{% static 'css/Index.css' %}" />
  <link rel="stylesheet" href="{% static 'css/ViewProfile.css' %}" />


    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"
    />
  </head>
  <body>

  {% include 'header.html' %}
  <br/>
    <div class="container">
        <div class="profile">
            <div class="profile-block">
                <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <h1>{{ title }}</h1>
                    {{ user_form.as_p }}
                    {{ profile_form.as_p }}
                    <br/>
                    <input class="btn btn-primary" type="submit" value="Save changes"/>
                </form>
            </div>
        </div>
    </div>
 <!--------------------------------------
FOOTER
--------------------------------------->
    <footer>
      <div class="footer-container">
        <div class="left-side">
          <strong>TeamUnexpected</strong>
          Copyright &copy; . All rights reserved.
        </div>
        <div class="Right-side">Made with TeamUnexpected.</div>
      </div>
    </footer>
    <!-- End Footer -->

  <script src={% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src={% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

CSE343-Software_Engineering/Term-Project/templates/accounts/form.html
{% load crispy_forms_tags %}
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Fitblog</title>
    <link rel="stylesheet" href="{% static 'css/Button.css' %}" />
    <link rel="stylesheet" href="{% static 'css/Link.css' %}" />
	<link rel="stylesheet" href="{% static 'css/Header.css' %}" />
	<link rel="stylesheet" href="{% static 'css/Footer.css' %}" />
	<link rel="stylesheet" href="{% static 'css/BlogIndex.css' %}" />

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"
    />
      <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>
  <body>

  {% include 'header.html' %}
  <br/>
    <div class="auth">
            <div class="col-md-12 col-md-offset-3">
                <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <h1>{{ title }}</h1>
                    {{ form|crispy }}
                    <br/>
                    <input class="btn btn-primary" type="submit" value="{{ title }}"/>
                </form>
            </div>
    </div>


  <script src={% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src={% static 'js/bootstrap.min.js' %}"></script>
  </body>
   <!--------------------------------------
FOOTER
--------------------------------------->
<footer>
  <div class="footer-container">
    <div class="left-side">
      <strong>TeamUnexpected</strong>
      Copyright &copy; . All rights reserved.
    </div>
    <div class="Right-side">Made with TeamUnexpected.</div>
  </div>
</footer>
<!-- End Footer -->
</html>

CSE343-Software_Engineering/Term-Project/templates/accounts/messages.html
{% if messages %}
    {% for message in messages %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
{% endif %}

CSE343-Software_Engineering/Term-Project/templates/accounts/password_reset.html
{% extends 'base.html' %} {% load crispy_forms_tags %} {% block body %}

<div class="Feedback">
  <div class="col-md-12 col-md-offset-3">

      <h1>Forgot your password?</h1>
  <p>Enter your email address below, and we'll email instructions for setting a new one.</p>

  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send me instructions!">
  </form>
      <br />
  </div>
</div>
{% endblock %}

CSE343-Software_Engineering/Term-Project/templates/accounts/password_reset_complete.html
{% extends 'base.html' %} {% load crispy_forms_tags %} {% block body %}
<div class="Feedback">
  <div class="col-md-12 col-md-offset-3">

     <p>
        Your password has been set. You may go ahead and <a href="{% url 'accounts:login' %}">sign in</a> now.
      </p>
  </div></div>
{% endblock %}

CSE343-Software_Engineering/Term-Project/templates/accounts/password_reset_confirm.html
{% extends 'base.html' %} {% load crispy_forms_tags %} {% block body %}
<div class="Feedback">
  <div class="col-md-12 col-md-offset-3">

{% if validlink %}
    <h3>Change password</h3>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Change password</button>
    </form>
  {% else %}
    <p>
      The password reset link was invalid, possibly because it has already been used.
      Please request a new password reset.
    </p>
      {% endif %}</div></div>
{% endblock %}

CSE343-Software_Engineering/Term-Project/templates/accounts/password_reset_done.html
{% extends 'base.html' %} {% load crispy_forms_tags %} {% block body %}

<div class="Feedback">
  <div class="col-md-12 col-md-offset-3">

      <p>
    We've emailed you instructions for setting your password, if an account exists with the email you entered.
    You should receive them shortly.
  </p>
  <p>
    If you don't receive an email, please make sure you've entered the address you registered with,
    and check your spam folder.
  </p>
      <br />
  </div>
</div>
{% endblock %}

CSE343-Software_Engineering/Term-Project/templates/accounts/password_reset_email.html
{% autoescape off %}
To initiate the password reset process for your {{ user.get_username }} FitUnexpected Account,
click the link below:

{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Sincerely,
The Team Unexpected
{% endautoescape %}

CSE343-Software_Engineering/Term-Project/templates/accounts/view_profile.html
{% load crispy_forms_tags %}
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Fitblog</title>


    <link rel="stylesheet" href="{% static 'css/Button.css' %}" />
    <link rel="stylesheet" href="{% static 'css/Link.css' %}" />
	<link rel="stylesheet" href="{% static 'css/Header.css' %}" />
	<link rel="stylesheet" href="{% static 'css/Footer.css' %}" />
	<link rel="stylesheet" href="{% static 'css/ViewProfile.css' %}" />
  

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"
    />
  </head>
  <body>

  {% include 'header.html' %}
  <br/>
    <div class="container">
        <div class="profile">
            <div class="profile-block">
              <div class="image">
                {% if user.profile.avatar_image %}
                   <img src="{{ user.profile.avatar_image.url }}" height="300"/>
                {% endif %}
              </div>
              <div class="inf">
                <h3>{{ user.first_name }} {{ user.last_name }}</h3>
                <p>E-mail address: {{ user.email }}</p>
                <p>Bio: {{ user.profile.bio }}</p>
                <p>City: {{ user.profile.location }}</p>
                <p>Birth Date: {{ user.profile.birth_date }}</p>
                <a href="{% url 'accounts:edit_profile' %}">Edit my profile</a>
              </div>
            </div>
        </div>
    </div>
 <!--------------------------------------
FOOTER
--------------------------------------->
    <footer>
      <div class="footer-container">
        <div class="left-side">
          <strong>TeamUnexpected</strong>
          Copyright &copy; . All rights reserved.
        </div>
        <div class="Right-side">Made with TeamUnexpected.</div>
      </div>
    </footer>
    <!-- End Footer -->

  <script src={% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src={% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>