CSE343-Software_Engineering/Term-Project/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from home.views import home_view
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name="home"),
    path('post/', include('post.urls')),
    path('accounts/', include('accounts.urls')),
    path('trainer/', include('trainer.urls')),
    path('feedback/', include('feedback.urls')),
    path("stripe/", include("djstripe.urls", namespace="djstripe")),
    path('messaging/', include('messaging.urls')),

    path('payment/', include('payment.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CSE343-Software_Engineering/Term-Project/payment/urls.py
from django.urls import path, re_path
from payment import views

app_name = 'payment'

urlpatterns = [
    #re_path(r'^charge/$', views.charge, name="charge"), 
    path('charge/<int:trainer_id>', views.charge, name='charge'),
]

CSE343-Software_Engineering/Term-Project/trainer/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'trainer'

urlpatterns = [
    path('index/', trainer_index, name='index'),
    re_path(r'^(?P<id>\d+)/$', trainer_detail, name='detail'),
    path('create/', trainer_create, name='create'),
    re_path(r'^(?P<id>[\w-]+)/update/$', trainer_update, name='update'),
    re_path(r'^(?P<id>[\w-]+)/delete/', trainer_delete, name='delete'),
    path('reservation/<int:id>', reservation, name='reservation'),
    path('reservationInfo/<int:id>/<str:date>/', reservationInfo, name='reservationInfo'),
]

CSE343-Software_Engineering/Term-Project/trainer/models.py
from django.db import models
from django.urls import reverse
from django.db.models import IntegerField, Model
from django.core.validators import MaxValueValidator, MinValueValidator


# Create your models here.
class Trainer(models.Model):
    Name= models.CharField(max_length=120)
    Surname = models.CharField(max_length=120)
    City = models.CharField(max_length=120)
    # Basinda 0 olmadan girilecek
    Phone = models.CharField(max_length=10)
    Mail = models.EmailField(max_length=120)
    gender_dict = [
        (True, 'Erkek'),
        (False, 'Kadın')
    ]
    Gender = models.BooleanField(blank=False, null=False, choices=gender_dict)
    Address = models.TextField()
    Work_Experience = models.TextField()
    image = models.FileField(null=True,blank=True)
    Birth_Date = models.DateField()
    approval_dict = [
        (True, 'Onaylı'),
        (False, 'Onaylanmamış')
    ]
    is_approved = models.BooleanField(default=False, verbose_name = 'Onay', choices=approval_dict)
    User_ID = models.ForeignKey('auth.User', related_name='trainers', on_delete=models.CASCADE, blank=True, null=True, verbose_name='Kullanıcı Hesabı')

    def __str__(self):
        return self.Name + ' ' + self.Surname

    def get_absolute_url(self):
        return reverse('trainer:detail', kwargs={'id': self.id})

    def get_send_message_url(self):
        return reverse('messaging:send_message', kwargs={'trainer_id': self.id})

class Comment(models.Model):
    trainer = models.ForeignKey('trainer.Trainer', related_name='comments', on_delete=models.CASCADE, verbose_name='Gönderi')
    name = models.CharField(max_length=200, verbose_name='Başlık')
    content = models.TextField(verbose_name='Yorum')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')

class CalendarEvent(models.Model):
    trainer = models.ForeignKey('trainer.Trainer', related_name='calendarevent', on_delete=models.CASCADE, verbose_name='Trainer')
    day_of_week_dict = [
        (0, 'Monday'),
        (1, 'Tuesday'),
        (2, 'Wednesday'),
        (3, 'Thursday'),
        (4, 'Friday'),
        (5, 'Saturday'),
        (6, 'Sunday'),
    ]
    day_of_week = models.IntegerField(default=0, verbose_name='Day of week', choices=day_of_week_dict)
    start_time = models.IntegerField(validators=[
            MaxValueValidator(23),
            MinValueValidator(0)
        ])
    def __str__(self):
        return self.trainer.Name + ' ' + self.trainer.Surname + ' | ' + str(self.day_of_week_dict[self.day_of_week][1] ) + ' | ' + str(self.start_time) + ":00"

class Reservation(models.Model):
    event = models.ForeignKey('CalendarEvent', related_name='reservation', on_delete=models.CASCADE, verbose_name='Calendar Event')
    trainer = models.ForeignKey('Trainer', related_name='reservation', on_delete=models.CASCADE, verbose_name='Trainer')
    customer = models.ForeignKey('auth.User', related_name='reservation', on_delete=models.CASCADE, blank=True, null=True, verbose_name='User')
    date_time = models.DateField( verbose_name='Reservation Date')

    def __str__(self):
        return self.customer.get_username() + ' ' + str(self.date_time) + " " + str(self.event.start_time) +":00"

CSE343-Software_Engineering/Term-Project/trainer/forms.py
from django import forms
from .models import Trainer, Comment

class TrainerForm(forms.ModelForm):

    class Meta:
        model = Trainer
        fields = [
            'Name',
            'Surname',
            'City',
            'Phone',
            'Gender',
            'Mail',
            'Address',
            'Work_Experience',
            'Birth_Date',
            'image'


        ]

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            'name',
            'content',
        ]

CSE343-Software_Engineering/Term-Project/trainer/views.py
from django.db.models.fields import DateField
from django.db.models.query import QuerySet
from django.shortcuts import render, HttpResponse, get_object_or_404, HttpResponseRedirect, Http404
from .models import CalendarEvent, Reservation, Trainer
from .forms import TrainerForm, CommentForm
from django.contrib import messages
from dict2xml import dict2xml
import datetime
from django.contrib.auth.decorators import login_required
from Product.models import Product
from django.core.mail import send_mail
from django.conf import settings
import jwt
import datetime
import requests
import json
import xml.etree.ElementTree as ET

def trainer_index(request):
    print("here")
    trainers = Trainer.objects.all()
    auth_trainer = None
    if request.user.is_authenticated:
        auth_trainer = trainers.filter(User_ID=request.user)

    return render(request, 'trainer/index.html', {'trainers': trainers, 'auth_trainer': auth_trainer})


def trainer_detail(request, id):
    trainer = get_object_or_404(Trainer, id=id)
    product = None
    product = Product.objects.all().first()

    disc_price = product.price * ((100 - product.discount_rate) / 100)

    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.trainer = trainer
        comment.save()
        return HttpResponseRedirect(trainer.get_absolute_url())

    context = {
        'trainer': trainer,
        'form': form,
        'product': product,
        'disc_price': disc_price,
    }

    return render(request, 'trainer/detail.html', context)


def trainer_create(request):
    form = TrainerForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        form.save()
    else:
        form = TrainerForm()
    context = {
        'form': form,
    }
    return render(request, 'trainer/form.html', context)


def trainer_update(request, id):
    if not request.user.is_authenticated:
        return Http404()

    trainer = get_object_or_404(Trainer, id=id)
    print(trainer.User_ID)
    form = TrainerForm(request.POST or None, request.FILES or None, instance=trainer)
    if form.is_valid():
        if request.user == trainer.User_ID:
            form.save()
            messages.success(request, 'Successfully updated!')
            return HttpResponseRedirect(trainer.get_absolute_url())
        else:
            messages.warning(request, 'You can not edit another trainer\'s information.')
            return redirect('trainer:index')
    context = {
        'form': form,
    }
    return render(request, 'trainer/form.html', context)


def trainer_delete(request):
    return HttpResponse('Burası trainer delete sayfası')


def add_calendar_event(request):
    return HttpResponse('Burası trainer delete sayfası')


def is_free_at(trainerId, date, hour):
    dateS = date.split('-')
    dayofweek = datetime.date(int(dateS[0]), int(dateS[1]), int(dateS[2])).weekday()

    isThereTheEvent = CalendarEvent.objects.filter(day_of_week=dayofweek, trainer=trainerId, start_time=hour)

    if (isThereTheEvent):
        rezervations = Reservation.objects.filter(date_time=date, trainer=trainerId)  # id ile query hata hata
        if (rezervations.exists()):
            for res in rezervations:
                print("resssssssssssssS::", res.event.start_time)
                if (res.event.start_time == hour):
                    return False
            return True
        else:
            return True
    else:
        return False





def free__lectures(trainerId, date):
    free_lecs = list()

    for a in range(0, 23):
        isFree = is_free_at(trainerId, date, a)
        print("is free ", a, ":", isFree)
        if (isFree):
            free_lecs.append(a)
    return free_lecs

    dateS = date.split('-')
    print("date::::::", dateS)
    dayofweek = datetime.date(int(dateS[0]), int(dateS[1]), int(dateS[2])).weekday()
    print("dayofweek:", dayofweek)
    events = CalendarEvent.objects.filter(day_of_week=dayofweek, trainer=trainerId)
    print("events::", events)

    free__lecs = list()
    for event in events:
        print("eve::", event)
        if (is_free_at(trainerId, date, event.start_time)):
            free__lecs.append(event)
            print("eventt:::", event)

    return free__lecs

def create_xml(list):
  
        # we make root element
        usrconfig = ET.Element("hours")
  
        # create sub element
        usrconfig = ET.SubElement(usrconfig, "hours")
  
        # insert list element into sub elements
        for user in range(len( list)):
  
                usr = ET.SubElement(usrconfig, "item")
                usr.text = str(list[user])
  
        tree = ET.ElementTree(usrconfig)
        
        return  ET.tostring(usrconfig, encoding="unicode")
        # write the tree into an XML file
        #tree.write("Output.xml", encoding ='utf-8', xml_declaration = True)
# Reservation part


def reservationInfo(request, id, date):
    free_lecs = free__lectures(id, date)

    a = [1, 2]
    data = {"free_lecs": free_lecs
            }

    xml = create_xml(free_lecs)
    print(xml)

    return HttpResponse(str(xml))


@login_required
def reservation(request, id):
    return render(request, 'trainer/calendar.html')

CSE343-Software_Engineering/Term-Project/templates/trainer/calendar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>CodePen - Simple Calendar</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.css"
    />
    <link rel="stylesheet" href="{% static 'css/calendar.css' %}" />
    <link rel="stylesheet" href="{% static 'css/book_button.css' %}" />
  </head>
  <body>
    <!-- partial:index.partial.html -->
    <script>
      function booking_hours(hourArray) {
        var table;
        for (var i = 0; i < hourArray.length; i++) {
          if (parseInt(hourArray[i].childNodes[0].nodeValue) < 9)
            table +=
              "<div data-hours='0" +
              hourArray[i].childNodes[0].nodeValue +
              ".00-0" +
              (parseInt(hourArray[i].childNodes[0].nodeValue) + 1) +
              ".00' class='hour_cell'>" +
              "<p>" +
              "0" +
              hourArray[i].childNodes[0].nodeValue +
              ".00 - 0" +
              (parseInt(hourArray[i].childNodes[0].nodeValue) + 1) +
              ".00" +
              "</p></div>";
          else if (parseInt(hourArray[i].childNodes[0].nodeValue) == 9) {
            table +=
              "<div data-hours='0" +
              hourArray[i].childNodes[0].nodeValue +
              ".00-0" +
              (parseInt(hourArray[i].childNodes[0].nodeValue) + 1) +
              ".00' class='hour_cell'>" +
              "<p>" +
              "0" +
              hourArray[i].childNodes[0].nodeValue +
              ".00 - " +
              (parseInt(hourArray[i].childNodes[0].nodeValue) + 1) +
              ".00" +
              "</p></div>";
          } else {
            table +=
              "<div data-hours='" +
              hourArray[i].childNodes[0].nodeValue +
              ".00-" +
              (parseInt(hourArray[i].childNodes[0].nodeValue) + 1) +
              ".00' class='hour_cell'>" +
              "<p>" +
              hourArray[i].childNodes[0].nodeValue +
              ".00 - " +
              (parseInt(hourArray[i].childNodes[0].nodeValue) + 1) +
              ".00" +
              "</p></div>";
          }
        }
        document.getElementById("hoursList").innerHTML = table.slice(9);
      }

      // fill the month table with column headings
      function day_title(day_name) {
        document.write("<div class='c-cal__col'>" + day_name + "</div>");
      }
      // fills the month table with numbers
      function fill_table(month, month_length, indexMonth) {
        day = 1;
        // begin the new month table
        document.write("<div class='c-main c-main-" + indexMonth + "'>");
        //document.write("<b>"+month+" "+year+"</b>")

        // column headings
        document.write("<div class='c-cal__row'>");
        day_title("Sun");
        day_title("Mon");
        day_title("Tue");
        day_title("Wed");
        day_title("Thu");
        day_title("Fri");
        day_title("Sat");
        document.write("</div>");

        // pad cells before first day of month
        document.write("<div class='c-cal__row'>");
        for (var i = 1; i < start_day; i++) {
          if (start_day > 7) {
          } else {
            document.write("<div class='c-cal__cel'></div>");
          }
        }

        // fill the first week of days
        for (var i = start_day; i < 8; i++) {
          document.write(
            "<div data-day='2017-" +
              indexMonth +
              "-0" +
              day +
              "'class='c-cal__cel'><p>" +
              day +
              "</p></div>"
          );
          day++;
        }
        document.write("</div>");

        // fill the remaining weeks
        while (day <= month_length) {
          document.write("<div class='c-cal__row'>");
          for (var i = 1; i <= 7 && day <= month_length; i++) {
            if (day >= 1 && day <= 9) {
              document.write(
                "<div data-day='2017-" +
                  indexMonth +
                  "-0" +
                  day +
                  "'class='c-cal__cel'><p>" +
                  day +
                  "</p></div>"
              );
              day++;
            } else {
              document.write(
                "<div data-day='2017-" +
                  indexMonth +
                  "-" +
                  day +
                  "' class='c-cal__cel'><p>" +
                  day +
                  "</p></div>"
              );
              day++;
            }
          }
          document.write("</div>");
          // the first day of the next month
          start_day = i;
        }

        document.write("</div>");
      }
    </script>
    <header>
      <div class="wrapper">
        <div class="c-monthyear">
          <a href="#" class="arrow left"></a>
          <div class="c-month">
            <span
              id="prev"
              class="prev fa fa-angle-left"
              aria-hidden="true"
            ></span>
            <div id="c-paginator">
              <span class="c-paginator__month">JANUARY</span>
              <span class="c-paginator__month">FEBRUARY</span>
              <span class="c-paginator__month">MARCH</span>
              <span class="c-paginator__month">APRIL</span>
              <span class="c-paginator__month">MAY</span>
              <span class="c-paginator__month">JUNE</span>
              <span class="c-paginator__month">JULY</span>
              <span class="c-paginator__month">AUGUST</span>
              <span class="c-paginator__month">SEPTEMBER</span>
              <span class="c-paginator__month">OCTOBER</span>
              <span class="c-paginator__month">NOVEMBER</span>
              <span class="c-paginator__month">DECEMBER</span>
            </div>
            <span
              id="next"
              class="next fa fa-angle-right"
              aria-hidden="true"
            ></span>
          </div>
          <div class="c-year">
            <span
              id="prevYear"
              class="prev fa fa-angle-left"
              aria-hidden="true"
            ></span>
            <div id="c-paginator">
              <span id="firstY" class="c-paginator__year"></span>
              <span id="secondY" class="c-paginator__year"></span>
              <span id="thirdY" class="c-paginator__year"></span>
            </div>
            <span
              id="nextYear"
              class="next fa fa-angle-right"
              aria-hidden="true"
            ></span>
          </div>
        </div>
      </div>
    </header>
    <div class="wrapper">
      <div class="c-calendar">
        <div class="c-calendar__style c-aside">
          <div class="c-aside__day">
            <span class="c-aside__num"></span>
            <span class="c-aside__month"></span>
            <span class="c-aside__year"></span>
          </div>

          <div id="hoursList" class="hours__list"></div>

          <button class="button">
            <div class="text">
              <p>B</p>
              <p>O</p>
              <p>O</p>
              <p>K</p>
              <p>!</p>
            </div>
          </button>
        </div>
        <div class="c-cal__container c-calendar__style">
          <script>
            // CAHNGE the below variable to the CURRENT YEAR
            year = 2017;

            // first day of the week of the new year
            today = new Date("January 1, " + year);
            start_day = today.getDay() + 1;
            fill_table("January", 31, "01");
            fill_table("February", 28, "02");
            fill_table("March", 31, "03");
            fill_table("April", 30, "04");
            fill_table("May", 31, "05");
            fill_table("June", 30, "06");
            fill_table("July", 31, "07");
            fill_table("August", 31, "08");
            fill_table("September", 30, "09");
            fill_table("October", 31, "10");
            fill_table("November", 30, "11");
            fill_table("December", 31, "12");
          </script>
        </div>
      </div>
    </div>
    <!-- partial -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.cycle2/2.1.6/jquery.cycle2.core.min.js"></script>
    <script src="{% static 'js/script.js' %}"></script>
  </body>
</html>

CSE343-Software_Engineering/Term-Project/templates/trainer/comment.html
{% load crispy_forms_tags %}

<form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <br/>
    <input type="submit" class="btn btn-primary" value="Yorum Ekle" />
</form>

CSE343-Software_Engineering/Term-Project/templates/trainer/detail.html
{% load static %}
<html>
  <head>
    <title>Profile Page</title>
    <link rel="stylesheet" href="{% static 'css/profile.css' %}" />
    <link rel="stylesheet" href="{% static 'css/Header.css' %}" />
    <link rel="stylesheet" href="{% static 'css/Footer.css' %}" />

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <style>
      .fa-star {
        opacity: 0.3;
        color: cadetblue;
      }
      .checked {
        opacity: 1;
        color: blue;
      }
    </style>
    <script
      src="https://kit.fontawesome.com/a076d05399.js"
      crossorigin="anonymous"
    ></script>
  </head>

  <body>
    {% include 'header.html' %}
    <div class="profile-box">
      <div class="left-side">
        <div class="image">
          <img src="{{trainer.image.url}}" alt="" />
        </div>
        <div class="experience">
          <h6>
            WORK
            <hr />
          </h6>

          <div>
            <p style="font-weight: bold">
              Spotify New York
              <b>Primary</b>
            </p>
            <p style="margin-top: 15px; color: grey; font-size: 0.9em">
              170 William Street<br />New York,NY 10038-78 212-312-51
            </p>
          </div>
          <div>
            <p style="font-weight: bold">
              Metropolitan
              <b>Secondary</b>
            </p>
            <p style="margin-top: 15px; color: grey; font-size: 0.9em">
              525 E 68th Street<br />New York,NY 10651-78 156-187-60
            </p>
          </div>
        </div>
        <div class="skills">
          <h6>WORK EXPERIENCE</h6>
          <hr />
          <ul>
            <li>{{ trainer.Work_Experience }}</li>
          </ul>
        </div>
      </div>

      <div class="right-side">
        <div class="upper-inf">
          <div class="personal-inf">
            <p style="font-size: 20px">
              {{trainer.Name}} {{trainer.Surname}}
              <i
                style="padding-left: 20px; font-size: 15px; opacity: 0.6"
                class="fa"
                >&#xf041; {{ trainer.Address }}</i
              >
            </p>
            <p style="margin-top: 5px; opacity: 0.8">
              <b style="font-size: 15px; color: lightblue">Trainer</b>
            </p>
          </div>

          <div class="ranking">
            <h6>Rankings</h6>
            <p style="margin-top: 5px; font-size: 20px; font-weight: bold">
              8,6
              <span class="fa fa-star checked"></span>
              <span class="fa fa-star checked"></span>
              <span class="fa fa-star checked"></span>
              <span class="fa fa-star"></span>
              <span class="fa fa-star"></span>
            </p>
          </div>
          <div class="alert-button">
            {% if request.user.is_authenticated %}

            <a href="{{ trainer.get_send_message_url }}"
              ><i style="font-size: 15px" class="fas">&#xf086;</i> Send
              Message</a
            >
            {% endif %}
          </div>
        </div>
        <div class="down-inf">
          <div class="down-info-buttons">
            <div id="btn"></div>

            <a href="#" class="toggle-btn">
              <i style="font-size: 14px" class="fas">&#xf406;</i> About
            </a>
            {% if request.user.is_authenticated %}
            <a href="{% url 'payment:charge' trainer.id %}" class="toggle-btn">
              <i style="font-size: 24px" class="fa">&#xf073;</i> Book
            </a>
            {% endif %}
          </div>

          <form id="About" class="input-group">
            <div class="about">
              <div class="contact">
                <h6>Contact Information</h6>

                <p style="color: blue">
                  <b style="color: black">Phone: </b> {{ trainer.Phone }}
                </p>
                <p><b>Adress: </b> {{ trainer.Address }}</p>

                <p style="color: blue">
                  <b style="color: black">E mail: </b> {{ trainer.Mail}}
                </p>
              </div>
              <div class="basic">
                <h6>Basic Information</h6>

                <p>
                  <b>Gender: </b> {% if trainer.Gender %} Male {% else %} Female
                  {% endif %}
                </p>

                <p><b>Birth Date: </b>{{trainer.Birth_Date}}</p>
              </div>
              <div class="basic">
                <h6>Payment Information</h6>

                <p>
                  <b>Monthly Price: </b>
                  {% if product %} {% if product.discount_rate > 0 %}
                  {{disc_price }} TRY (%{{product.discount_rate}} Discount)
                  {%else %} {{ product.price }} TRY {% endif %} {% endif %}
                </p>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>

    <script type="text/javascript">
      //Javacript for responsive navigation menu
      const menuBtn = document.querySelector(".menu-btn");
      const navigation = document.querySelector(".navigation");

      menuBtn.addEventListener("click", () => {
        menuBtn.classList.toggle("active");
        navigation.classList.toggle("active");
      });
    </script>
  </body>
  <!--------------------------------------
FOOTER
--------------------------------------->
  <footer>
    <div class="footer-container">
      <div class="left-side">
        <strong>TeamUnexpected</strong>
        Copyright &copy; . All rights reserved.
      </div>
      <div class="Right-side">Made with TeamUnexpected.</div>
    </div>
  </footer>
  <!-- End Footer -->
</html>

CSE343-Software_Engineering/Term-Project/templates/trainer/form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}

    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <h1>Update Trainers</h1>
                    {{ form|crispy }}
                    {{ form.media }}
                    <br/>
                    <input class="btn btn-primary" type="submit" value="Gönder"/>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

CSE343-Software_Engineering/Term-Project/templates/trainer/index.html
{% load static %}
<html>
  <head>
    <title>Trainers Page</title>
    <link rel="stylesheet" href="{% static 'css/Trainers.css' %}" />
    <link rel="stylesheet" href="{% static 'css/Header.css' %}" />
    <link rel="stylesheet" href="{% static 'css/Footer.css' %}" />

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"
    />
    <link rel="stylesheet" href="{% static 'css/Button.css' %}" />

    <style>
      .fa-star {
        opacity: 0.3;
        color: cadetblue;
      }
      .checked {
        opacity: 1;
        color: blue;
      }
    </style>
    <script
      src="https://kit.fontawesome.com/a076d05399.js"
      crossorigin="anonymous"
    ></script>
  </head>

  <body>
    {% include 'header.html' %}

    <div class="profile-list">
      {% if auth_trainer %} {% endif %}
      <div class="trainer-blocks">
        {% for trainer in trainers %}
        <div class="profile-block">
          <div class="upper-side">
            <img src="{{ trainer.image.url }}" alt="" />
            <div class="profile-inf">
              <p>{{ trainer.Name}} {{ trainer.Surname }}</p>
              <div class="ranking">
                <h6>Rankings</h6>
                <p style="margin-top: 5px; font-size: 20px; font-weight: bold">
                  8,6
                  <span class="fa fa-star checked"></span>
                  <span class="fa fa-star checked"></span>
                  <span class="fa fa-star checked"></span>
                  <span class="fa fa-star"></span>
                  <span class="fa fa-star"></span>
                </p>
              </div>
              <p>{{ trainer.Address }}</p>
            </div>
          </div>
          <div class="down-side">
            <a href="{{trainer.get_absolute_url}}">
              <button
                style="justify-items: end; margin-top: 10px"
                class="button-75"
                role="button"
              >
                <p class="text">Profile</p>
              </button></a
            >
          </div>
        </div>
        <br />
        {% endfor %}
      </div>
    </div>
    <script type="text/javascript">
      //Javacript for responsive navigation menu
      const menuBtn = document.querySelector(".menu-btn");
      const navigation = document.querySelector(".navigation");

      menuBtn.addEventListener("click", () => {
        menuBtn.classList.toggle("active");
        navigation.classList.toggle("active");
      });
    </script>
    <script>
      var x = document.getElementById("About");
      var y = document.getElementById("Calender");
      var z = document.getElementById("btn");

      function about() {
        x.style.left = "-480px";
        y.style.left = "500px";
        z.style.left = "170px";
      }
      function calender() {
        x.style.left = "0px";
        y.style.left = "0px";
        z.style.left = "0px";
      }
    </script>
  </body>
  <!--------------------------------------
FOOTER
--------------------------------------->
  <footer>
    <div class="footer-container">
      <div class="left-side">
        <strong>TeamUnexpected</strong>
        Copyright &copy; . All rights reserved.
      </div>
      <div class="Right-side">Made with TeamUnexpected.</div>
    </div>
  </footer>
  <!-- End Footer -->
</html>