CSE343-Software_Engineering/Term-Project/accounts/urls.py
from django.urls import path, re_path, reverse_lazy, include
from .views import *
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('register/', signup, name='register'),
    path('logout/', logout_view, name='logout'),
    path('profile/', view_profile, name='profile'),
    path('edit_profile/', update_profile, name='edit_profile'),
    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='accounts/password_reset.html',
        email_template_name='accounts/password_reset_email.html',
        subject_template_name='accounts/password_reset_subject.txt',
        success_url=reverse_lazy('accounts:password_reset_done')
    ), name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(
        template_name='accounts/password_reset_done.html'
    ), name='password_reset_done'),
    path('password_reset_<uidb64>_<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='accounts/password_reset_confirm.html',
        success_url=reverse_lazy('accounts:password_reset_complete')
    ), name='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='accounts/password_reset_complete.html'
    ), name='password_reset_complete'),
]

CSE343-Software_Engineering/Term-Project/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from home.views import home_view
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name="home"),
    path('post/', include('post.urls')),
    path('accounts/', include('accounts.urls')),
    path('trainer/', include('trainer.urls')),
    path('feedback/', include('feedback.urls')),
    path("stripe/", include("djstripe.urls", namespace="djstripe")),
    path('messaging/', include('messaging.urls')),

    path('payment/', include('payment.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CSE343-Software_Engineering/Term-Project/feedback/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'feedback'

urlpatterns = [
    path('index/', feedback_index, name='index'),
]

CSE343-Software_Engineering/Term-Project/post/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'post'

urlpatterns = [
    path('index/', post_index, name='index'),
    path('create/', post_create, name='create'),
    path('categories/', category_view, name='categories'),
    re_path(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
    re_path(r'^(?P<slug>[\w-]+)/update/$', post_update, name='update'),
    re_path(r'^(?P<slug>[\w-]+)/delete/', post_delete, name='delete'),
]

CSE343-Software_Engineering/Term-Project/trainer/urls.py
from django.urls import path, re_path
from .views import *

app_name = 'trainer'

urlpatterns = [
    path('index/', trainer_index, name='index'),
    re_path(r'^(?P<id>\d+)/$', trainer_detail, name='detail'),
    path('create/', trainer_create, name='create'),
    re_path(r'^(?P<id>[\w-]+)/update/$', trainer_update, name='update'),
    re_path(r'^(?P<id>[\w-]+)/delete/', trainer_delete, name='delete'),
    path('reservation/<int:id>', reservation, name='reservation'),
    path('reservationInfo/<int:id>/<str:date>/', reservationInfo, name='reservationInfo'),
]

CSE343-Software_Engineering/Term-Project/home/models.py
from django.db import models

# Create your models here.

CSE343-Software_Engineering/Term-Project/home/views.py
from django.shortcuts import render, HttpResponse

def home_view(request):
    return render(request, 'home.html',)

CSE343-Software_Engineering/Term-Project/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content="width-device-width, initial-scale=1">
    <title>{% block title %}Fit Blog{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/Header.css' %}" />
    <link rel="stylesheet" href="{% static 'css/Footer.css' %}" />


</head>
<body>

    {% include 'messages.html' %}

    {% include 'header.html' %}

    {% block body %}

    {% endblock %}

    <script src={% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src={% static 'js/bootstrap.min.js' %}"></script>

</body>
 <!--------------------------------------
FOOTER
--------------------------------------->
<footer>
    <div class="footer-container">
      <div class="left-side">
        <strong>TeamUnexpected</strong>
        Copyright &copy; . All rights reserved.
      </div>
      <div class="Right-side">Made with TeamUnexpected.</div>
    </div>
  </footer>
  <!-- End Footer -->
</html>

CSE343-Software_Engineering/Term-Project/templates/header.html
<!--------------------------------------
    HEADER
    --------------------------------------->
<header>
  <div class="navbar">
    <div class="brand">
      <a href="http://127.0.0.1:8000/">
        <img
          src="/static/Images/FİTUNEXPECTED.png"
          alt="Error!"
          width="150px"
          height="75px"
        />
      </a>
    </div>
    <div class="auth-buttons">
      <div class="navigation-items">
        {% if not request.user.is_authenticated %}
        <a style="font-weight: bold" href="{% url 'accounts:login' %}"
          >Log In</a
        >
        <a style="font-weight: bold" href="{% url 'accounts:register' %}"
          >Sign Up</a
        >
        <a style="font-weight: bold" href="{% url 'accounts:password_reset' %}"
          >Forgot Password</a
        >
        {% else %}

        <a
          href="{% url 'accounts:profile' %}"
          style="font-size: 24px"
          class="far"
          >&#xf2bd;</a
        >
        <a style="font-weight: bold" href="{% url 'messaging:index' %}">
          <i style="font-size: 24px" class="fa">&#xf0e0;</i>
        </a>

        <a style="font-weight: bold" href="{% url 'accounts:logout' %}"
          >Log Out</a
        >
        {% endif %}
      </div>
    </div>
    <div class="menu-btn"></div>
    <div class="navigation" style="">
      <div class="navigation-items">
        <a style="font-weight: bold" href="{% url 'post:index' %}">Blog</a>
        <a style="font-weight: bold" href="{% url 'trainer:index' %}"
          >Trainers</a
        >

        <a style="font-weight: bold" href="{% url 'feedback:index' %}"
          >Feedback</a
        >
        <a style="font-weight: bold" href="#">About Us</a>
      </div>
    </div>
  </div>
</header>
<!-- End Header -->

CSE343-Software_Engineering/Term-Project/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Fitblog</title>
    <link rel="stylesheet" href="{% static 'css/Mainindex1.css' %}" />
    <link rel="stylesheet" href="{% static 'css/Header.css' %}" />
    <link rel="stylesheet" href="{% static 'css/Footer.css' %}" />

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"
    />
  </head>
  <body>
    {% include 'header.html' %}

    <section class="home">
      <video
        class="video-slide active"
        src="{% static 'Videos/1.webm' %}"
        autoplay
        muted
        loop
      ></video>
      <video
        class="video-slide"
        src="{% static 'Videos/2.mp4' %}"
        autoplay
        muted
        loop
      ></video>
      <video
        class="video-slide"
        src="{% static 'Videos/3.mp4' %}"
        autoplay
        muted
        loop
      ></video>
      <video
        class="video-slide"
        src="{% static 'Videos/4.mp4' %}"
        autoplay
        muted
        loop
      ></video>
      <video
        class="video-slide"
        src="{% static 'Videos/5.mp4' %}"
        autoplay
        muted
        loop
      ></video>
      <div class="content active">
        <h1>Wonderful<br /><span>Workouts...</span></h1>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
          minim veniam, quis nostrud exercitation ullamco laboris nisi ut
          aliquip ex ea commodo consequat. Duis aute irure dolor in
          reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
          pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
          culpa qui officia deserunt mollit anim id est laborum.
        </p>
        <a href="#">Read More</a>
      </div>
      <div class="content">
        <h1>Make Training<br /><span>Anywhere</span></h1>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
          minim veniam, quis nostrud exercitation ullamco laboris nisi ut
          aliquip ex ea commodo consequat. Duis aute irure dolor in
          reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
          pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
          culpa qui officia deserunt mollit anim id est laborum.
        </p>
        <a href="#">Read More</a>
      </div>
      <div class="content">
        <h1>NO PAİN<br /><span>NO GAIN</span></h1>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
          minim veniam, quis nostrud exercitation ullamco laboris nisi ut
          aliquip ex ea commodo consequat. Duis aute irure dolor in
          reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
          pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
          culpa qui officia deserunt mollit anim id est laborum.
        </p>
        <a href="#">Read More</a>
      </div>
      <div class="content">
        <h1>Trip<br /><span>For Lesson</span></h1>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
          minim veniam, quis nostrud exercitation ullamco laboris nisi ut
          aliquip ex ea commodo consequat. Duis aute irure dolor in
          reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
          pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
          culpa qui officia deserunt mollit anim id est laborum.
        </p>
        <a href="#">Read More</a>
      </div>
      <div class="content">
        <h1>Feel Nature.<br /><span>Relax</span></h1>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
          minim veniam, quis nostrud exercitation ullamco laboris nisi ut
          aliquip ex ea commodo consequat. Duis aute irure dolor in
          reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
          pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
          culpa qui officia deserunt mollit anim id est laborum.
        </p>
        <a href="#">Read More</a>
      </div>
      <div class="media-icons">
        <a href="#"><i class="fab fa-facebook-f"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
      </div>
      <div class="slider-navigation">
        <div class="nav-btn active"></div>
        <div class="nav-btn"></div>
        <div class="nav-btn"></div>
        <div class="nav-btn"></div>
        <div class="nav-btn"></div>
      </div>
    </section>

    <script type="text/javascript">
      //Javacript for responsive navigation menu
      const menuBtn = document.querySelector(".menu-btn");
      const navigation = document.querySelector(".navigation");

      menuBtn.addEventListener("click", () => {
        menuBtn.classList.toggle("active");
        navigation.classList.toggle("active");
      });

      //Javacript for video slider navigation
      const btns = document.querySelectorAll(".nav-btn");
      const slides = document.querySelectorAll(".video-slide");
      const contents = document.querySelectorAll(".content");

      var sliderNav = function (manual) {
        btns.forEach((btn) => {
          btn.classList.remove("active");
        });

        slides.forEach((slide) => {
          slide.classList.remove("active");
        });

        contents.forEach((content) => {
          content.classList.remove("active");
        });

        btns[manual].classList.add("active");
        slides[manual].classList.add("active");
        contents[manual].classList.add("active");
      };

      btns.forEach((btn, i) => {
        btn.addEventListener("click", () => {
          sliderNav(i);
        });
      });
    </script>
  </body>
  <!--------------------------------------
FOOTER
--------------------------------------->
  <footer>
    <div class="footer-container">
      <div class="left-side">
        <strong>TeamUnexpected</strong>
        Copyright &copy; . All rights reserved.
      </div>
      <div class="Right-side">Made with TeamUnexpected.</div>
    </div>
  </footer>
  <!-- End Footer -->
</html>

CSE343-Software_Engineering/Term-Project/templates/messages.html
{% if messages %}
    {% for message in messages %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
{% endif %}

CSE343-Software_Engineering/Term-Project/templates/success.html
<html>
  <title>Success</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>
  <style>
    body {
      text-align: center;
      padding: 40px 0;
      background: #003567;
    }
    h1 {
      color: #308adf;
      font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
      font-weight: 900;
      font-size: 40px;
      margin-bottom: 10px;
    }
    p {
      color: #404f5e;
      font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
      font-size: 20px;
      margin: 0;
    }
    i {
      color: #308adf;
      font-size: 100px;
      line-height: 200px;
      margin-left: -15px;
    }
    .card {
      background: white;
      padding: 60px;
      border-radius: 4px;
      box-shadow: 0 2px 3px #c8d0d8;
      display: inline-block;
      margin: 0 auto;
    }
  </style>
  <body>
    <div class="card">
      <div
        style="
          border-radius: 200px;
          height: 200px;
          width: 200px;
          background: #f8faf5;
          margin: 0 auto;
          display: flex;
          justify-content: center;
          align-items: center;
        "
      >
        <a href="http://127.0.0.1:8000/"><i style="font-size: 100px" class="fa">&#xf00c;</i> </a>
      </div>
      <h1>Success</h1>
      <p>
        We received your purchase request;<br />
        we'll be in touch shortly!
      </p>
    </div>
  </body>
</html>